name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: current
    - name: Setup webpack
      run: (cd webpack/test_env && npm install)
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
